config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'spgateway/return'
  post "spgateway/notify"
  
  root "products#index"
    resources :products, only: [:index, :show] do
      post :add_to_cart, on: :member
      post :remove_from_cart, on: :member
      post :adjust_item, on: :member
    end
    resource :cart
    resources :orders do
      post :checkout_spgateway, on: :member
    end

    namespace :admin do
      root "products#index"
      resources :products
      resources :orders
    end

end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, presence: true
  validates :price, presence: true
  mount_uploader :image, PhotoUploader

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

    def index
      @products = Product.page(params[:page]).per(15)
    end

    def new
      @product = Product.new
    end

    def create
      @product = Product.new(product_params)
      if @product.save
        redirect_to admin_products_path, notice: "product was successfully created"
      else
        render :new
      end
    end

    def update
      if @product.update(product_params)
        redirect_to admin_product_path(@product), notice: "product was successfully updated"
      else
        render :edit
      end
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path, alert: "product was deleted"
    end

    

    private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(50)
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    current_cart.add_cart_item(@product)

   # redirect_back(fallback_location: root_path)
  end

  def remove_from_cart
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    cart_item.destroy

    # redirect_back(fallback_location: root_path)
  end

  def adjust_item
    @product = Product.find(params[:id])
    cart_item = current_cart.cart_items.find_by(product_id: @product)
    if params[:type] == "add"
      cart_item.quantity += 1
    elsif params[:type] == "substract"
      cart_item.quantity -= 1
    end

    if cart_item.quantity == 0
      cart_item.destroy
    else
      cart_item.save
    end
    # redirect_back(fallback_location: root_path)
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/add_to_cart.js.erb
<% item = current_cart.find_item_by(@product) %>
<% if item.quantity == 1 %>
  $('.item-list').append('<%= j render partial: "shared/item", locals: { item: item } %>');
<% else %>
  $('.cart-<%= @product.id %>-qty').text("<%= item.quantity %>");
<% end %>

$('.amount').text('<%= current_cart.subtotal %>')

app/views/products/adjust_item.js.erb
<% item = current_cart.find_item_by(@product) %>
<% if !item %>
  $('.product-<%= @product.id %>').remove();
<% else %>
  $('.cart-<%= @product.id %>-qty').text("<%= item.quantity %>");
  $('.item-<%= @product.id%>-total').text("<%= item.item_total %>");
<% end %>
$('.amount').text('<%= current_cart.subtotal %>')

app/views/products/index.html.erb
<div class="container">
   <div class="row">
     <ul class="nav nav-tabs">
        <li role="presentation" class="active">
         <%= link_to 'Products', admin_products_path %>
        </li>
        <li role="presentation">
         <%= link_to 'Orders', admin_orders_path %>
        </li>

     </ul>
   </div>
 </div>
   <br>

<%= render "shared/cart" %>

<section id="product-list">
  <% @products.each do |product| %>
   <div class="product-box product_<%= product.id %>">
     <%= link_to product_path(product) do %>
       <%= image_tag product.image %><br>
       <%= product.name %><br>
     <% end %>
     $<%= product.price %>
    <%= button_to 'Add to Cart', add_to_cart_product_path(product), remote: true %>
   </div>

  <% end %>
</section>

 <%= paginate @products %>

app/views/products/remove_from_cart.js.erb
$('.product-<%= @product.id %>').remove();
$('.amount').text('<%= current_cart.subtotal %>')

app/views/products/show.html.erb
<%= render "shared/cart" %>

<%= image_tag(@product.image, width: 100 ) %>

<h3><%= @product.name %></h3>
<h5>$ <%= @product.price %></h5>
<%= simple_format @product.description %>

<%= button_to 'Add to Cart', add_to_cart_product_path(@product), remote: true %>